# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hyperfoil
email: hyperfoil@hyperfoil.io
description: >- # this means to ignore newlines until "baseurl:"
  Microservice-oriented distributed benchmark framework.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyperfoil.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hyperfoil-does-not-tweet
github_username:  Hyperfoil
github:
  is_project_page: true
  repository_nwo: Hyperfoil/Hyperfoil
  repository_url: https://github.com/Hyperfoil/Hyperfoil

last_release:
  zip: hyperfoil-0.9.zip
  dir: hyperfoil-0.9
  tag: release-0.9
  galaxy_version: "0.9"
  url: https://github.com/Hyperfoil/Hyperfoil/releases/download/release-0.9/hyperfoil-0.9.zip

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# We use highlight.js explicitly
kramdown:
   syntax_highlighter_opts:
      disable : true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
